DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS plix;

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  name VARCHAR NOT NULL UNIQUE,
  password_digest VARCHAR NOT NULL
);

CREATE TABLE locations (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  place_id VARCHAR NOT NULL,
  address VARCHAR(80) NOT NULL,
  lat FLOAT NOT NULL,
  lng FLOAT NOT NULL
);

CREATE TABLE plix (
  id BIGSERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  location_id INT REFERENCES locations(id) ON DELETE CASCADE NOT NULL,
  img VARCHAR NOT NULL,
  thumb VARCHAR,
  description VARCHAR(255) NOT NULL,
  plix_date DATETIME NOT NULL DEFAULT NOW()
);